services:
  - type: web
    name: thobe-plus-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false 